name: Build and Release Apps Linux Only
on: [workflow_dispatch]
jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install Depends
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Enabled linux app
        run: flutter config --enable-linux-desktop
      - name: Build Linux App
        run: |
          flutter build linux --release
          cd build/linux/x64/release/bundle
          zip -r linux-app-x64.zip .
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: Azkadev App
          token: ${{ secrets.TOKEN }}
          artifacts: 'build/linux/x64/release/bundle/linux-app-x64.zip'
